### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by ChessWaveIO** [renchizhhhh/OpenChessRobot#1]
- The following link in the readme is broken, I can't clone the dependency:

https://github.com/blackholebug/chess_panda_ros.git

- The following link in the readme is also broken:

https://schaakwinkel.nl/schaakborden/Schaakbord-SB10

- Can you provide a link to the 3d meshes for pieces and boards? 

Thanks!

**Comment by renchizhhhh** [comment]
Hi there, the git link is fixed in the Readme now. For the link of the chess board, it seems that the board I used is out of stock for the moment. There is a similar one but with different texture: [link](https://schaakwinkel.nl/products/schaakbord-mahonie-ahorn-afm-48-cm-x-48-cm-veld-50-mm-met-coordinaten). For board of other sizes, it should also work but you need to adjust some parameters for the localization and robot grasping. 

For the 3D model of the chess pieces and board, I didn't use/have the 3D scan of the real-world piece or board. I made my synthetic images using [this](https://assetstore.unity.com/packages/3d/props/3d-wooden-chess-set-183336) and then did the transfer learning with the real world chess set (only rgb images). 

However, another project did the 3D scan for the pieces and you can check out this [repo](https://github.com/maxiew123/Thesis-Robotics-Max-Waterhout.git).

**Comment by ChessWaveIO** [comment]
Thanks, that answers all of my questions!
